const ALLOW_DAY = 'AVAILABILITY::ALLOW_DAY';
const BLOCK_DAY = 'AVAILABILITY::BLOCK_DAY';
const CHANGE_MONTH = 'AVAILABILITY::CHANGE_MONTH';
const SAVE_CHANGES = 'AVAILABILITY::SAVE_CHANGES';
const CLOSE_EDIT_VIEW = 'AVAILABILITY::CLOSE_EDIT_VIEW';

export {
  ALLOW_DAY,
  BLOCK_DAY,
  CHANGE_MONTH,
  SAVE_CHANGES,
  CLOSE_EDIT_VIEW,
};
